### ISSUE TITLE
use get_site_url() instead of get_home_url()

### ISSUE THREAD

**Issue by Vinsanity** [3five/Custom-User-Profile-Photo#4]
SOMTIJDS wrote:

First of all, thanks for a great plugin! This is not really a support request, just a pointer, I suppose - I was looking for a Github repo to open an issue there, but couldn't find it. So here it is:
I was wondering: in line 77 of the plugin file you're using get_home_url to build up the edit url:
        `$cupp_upload_edit_url = get_home_url().get_the_author_meta( 'cupp_upload_edit_meta', $user->ID );`
My suggestion would be to use get_site_url() here. For me, the plugin causes a 404 when clicking on the (nicely implemented!) edit link - as I'm used to putting WordPress in its own folder. The issue is solved after changing this into
`$cupp_upload_edit_url = get_site_url().get_the_author_meta( 'cupp_upload_edit_meta', $user->ID );`
Maybe it's my setup, surely there are .htaccess files that would fix this. But get_site_url() seems the safer choice here, no?
https://wordpress.org/plugins/custom-user-profile-photo/
Post Link: https://wordpress.org/support/topic/edit-url-incorrect-for-wp-subfolder-installations?replies=1#post-8419059

**Comment by jmichaelward** [comment]
I was able to replicate this using our Rudiments Stack, so I've made this change. It is included with the latest pull request.

**Comment by jmichaelward** [comment]
@Vinsanity I discovered that my implementation of this in the `development` branch was incorrect.

In `feature/#2`, I restructured the logic that determines which current image and interactions get displayed, and opted instead to build the edit url based on the upload path (instead of retrieving it from saved metadata). This appears to be consistent and correct, so I expect that we'll be able to close this issue once `feature/#2` is merged in.
