### ISSUE TITLE
issue with get_user_by( 'email' ) using postID instead of user ID in some cases.

### ISSUE THREAD

**Issue by Vinsanity** [3five/Custom-User-Profile-Photo#5]
Hi,

I use the "Custom User Profile Photo Version 0.4" plugin and I think there's a bug in cupp_avatar(). When get_avatar() is called with an email as the first parameter ($id_or_email) cupp_avatar() will reach line 232 where it queries user by email. However after this the $id variable is not set if the value returned by get_user_by() is a valid value. Without setting $id the current post's user and its avatar would be used.

See my diff below:
## `

diff --git a/wp-content/plugins/custom-user-profile-photo/3five_cupp.php b/wp-content/plugins/custom-user-profile-photo/3five_cupp.php
index ce0d91a..e465843 100644
--- a/wp-content/plugins/custom-user-profile-photo/3five_cupp.php
+++ b/wp-content/plugins/custom-user-profile-photo/3five_cupp.php
@@ -229,7 +229,11 @@ function cupp_avatar( $avatar, $id_or_email, $size, $default, $alt ) {

```
 } else {
     // $id = (int) $id_or_email;
```
-        $user = get_user_by( 'email', $id_or_email );  
-        $user = get_user_by( 'email', $id_or_email );
-        // set $id, which will be used by get_cupp_meta().
-        if ( $user && is_object( $user )) {
-            $id = $user->ID;
- ```
     }
  ```
  
   }
  ##  if ( $user && is_object( $user ) ) {
  
  `
  Hope you can fix it in the release. 

Keep up the good work! :-)
## Thanks,

balazs

**Comment by jmichaelward** [comment]
@Vinsanity I heavily updated and simplified the logic of this in my latest pull request, wherein I added a method called `cupp_get_user_by_id_or_email` that returns a call to `get_user_by` depending on the parameter checks that are in place. If `get_user_by` finds anything, it'll return a `WP_User` object, otherwise it returns false.

In this case, instead of checking whether the passed identifier is an object, I check if the identifier contains a property called `user_id`, and if it does, we run a query to get that `WP_User`. I suspect that should resolve this issue.

**Comment by jmichaelward** [comment]
@Vinsanity I tested this in the development branch, and I get the correct user avatars when calling `get_avatar` and passing in an e-mail address.

In feature/#2, this is further improved, because the image that was uploaded through a Gravity Form is also correctly displayed, instead of the default avatar.
